### ISSUE TITLE
docker build error related to dependencies?

### ISSUE THREAD

**Issue by jeroenterheerdt** [OttPeterR/addon-babybuddy#21] opened 2022-11-04 16:44 UTC
![image](https://user-images.githubusercontent.com/8188990/200029804-fd519504-392d-40d3-b87f-cd0e559c7669.png)

This is what is in the Supervisor log:
```
**** install build packages ****
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/armv7/APKINDEX.tar.gz
ERROR: unable to select packages:

  musl-1.2.3-r0:
    breaks: musl-dev-1.2.3-r1[musl=1.2.3-r1]
    satisfies: world[musl=1.2.3-r0]
               apk-tools-2.12.9-r3[musl>=1.2]
               apk-tools-2.12.9-r3[so:libc.musl-armv7.so.1]
               pkgconf-1.8.0-r1[so:libc.musl-armv7.so.1]
               llvm13-13.0.1-r2[so:libc.musl-armv7.so.1]
               gcc-11.2.1_git20220219-r2[so:libc.musl-armv7.so.1]
               clang-13.0.1-r1[so:libc.musl-armv7.so.1]
               icu-dev-71.1-r2[so:libc.musl-armv7.so.1]
               g++-11.2.1_git20220219-r2[so:libc.musl-armv7.so.1]
               libffi-3.4.2-r1[so:libc.musl-armv7.so.1]
               tzdata-2022c-r0[so:libc.musl-armv7.so.1]
               patch-2.7.6-r7[so:libc.musl-armv7.so.1]
               libjpeg-turbo-2.1.3-r1[so:libc.musl-armv7.so.1]
               libxslt-1.1.35-r0[so:libc.musl-armv7.so.1]
               bash-5.1.16-r2[so:libc.musl-armv7.so.1]
               ca-certificates-20220614-r0[so:libc.musl-armv7.so.1]
               python3-3.10.5-r0[so:libc.musl-armv7.so.1]
               binutils-2.38-r3[so:libc.musl-armv7.so.1]
               busybox-1.35.0-r17[so:libc.musl-armv7.so.1]
               libecpg-dev-14.5-r0[so:libc.musl-armv7.so.1]
               sqlite-libs-3.38.5-r0[so:libc.musl-armv7.so.1]
               curl-7.83.1-r2[so:libc.musl-armv7.so.1]
               ncurses-libs-6.3_p20220521-r0[so:libc.musl-armv7.so.1]
               expat-2.5.0-r0[so:libc.musl-armv7.so.1]
               musl-utils-1.2.3-r0[so:libc.musl-armv7.so.1]
               nghttp2-libs-1.47.0-r0[so:libc.musl-armv7.so.1]
               llvm13-libs-13.0.1-r2[so:libc.musl-armv7.so.1]
               libstdc++-11.2.1_git20220219-r2[so:libc.musl-armv7.so.1]
               mpdecimal-2.5.1-r1[so:libc.musl-armv7.so.1]
               libbz2-1.0.8-r1[so:libc.musl-armv7.so.1]
               brotli-libs-1.0.9-r6[so:libc.musl-armv7.so.1]
               libpq-14.5-r0[so:libc.musl-armv7.so.1]
               libpq-dev-14.5-r0[so:libc.musl-armv7.so.1]
               clang-libs-13.0.1-r1[so:libc.musl-armv7.so.1]
               file-5.41-r0[so:libc.musl-armv7.so.1]
               icu-71.1-r2[so:libc.musl-armv7.so.1]
               libcurl-7.83.1-r2[so:libc.musl-armv7.so.1]
               mpc1-1.2.1-r0[so:libc.musl-armv7.so.1]
               libmagic-5.41-r0[so:libc.musl-armv7.so.1]
               gdbm-1.23-r0[so:libc.musl-armv7.so.1]
               icu-libs-71.1-r2[so:libc.musl-armv7.so.1]
               oniguruma-6.9.8-r0[so:libc.musl-armv7.so.1]
               mpfr4-4.1.0-r0[so:libc.musl-armv7.so.1]
               zlib-1.2.12-r3[so:libc.musl-armv7.so.1]
               libgomp-11.2.1_git20220219-r2[so:libc.musl-armv7.so.1]
               readline-8.1.2-r0[so:libc.musl-armv7.so.1]
               libecpg-14.5-r0[so:libc.musl-armv7.so.1]
               make-4.3-r0[so:libc.musl-armv7.so.1]
               libgpg-error-1.45-r0[so:libc.musl-armv7.so.1]
               libgcc-11.2.1_git20220219-r2[so:libc.musl-armv7.so.1]
               postgresql14-dev-14.5-r0[so:libc.musl-armv7.so.1]
               libssl1.1-1.1.1q-r0[so:libc.musl-armv7.so.1]
               alpine-baselayout-3.2.0-r22[so:libc.musl-armv7.so.1]
               libcrypto1.1-1.1.1q-r0[so:libc.musl-armv7.so.1]
               libatomic-11.2.1_git20220219-r2[so:libc.musl-armv7.so.1]
               xz-libs-5.2.5-r1[so:libc.musl-armv7.so.1]
               libxml2-2.9.14-r2[so:libc.musl-armv7.so.1]
               scanelf-1.3.4-r0[so:libc.musl-armv7.so.1]
               gmp-6.2.1-r2[so:libc.musl-armv7.so.1]
               jq-1.6-r1[so:libc.musl-armv7.so.1]
               libgcrypt-1.10.1-r0[so:libc.musl-armv7.so.1]
               isl22-0.22-r0[so:libc.musl-armv7.so.1]
  libcrypto1.1-1.1.1q-r0:
    breaks: openssl-dev-1.1.1s-r0[libcrypto1.1=1.1.1s-r0]
    satisfies: world[libcrypto1.1=1.1.1q-r0]
               ca-certificates-20220614-r0[so:libcrypto.so.1.1]
               python3-3.10.5-r0[so:libcrypto.so.1.1]
               libpq-14.5-r0[so:libcrypto.so.1.1]
               libcurl-7.83.1-r2[so:libcrypto.so.1.1]
               apk-tools-2.12.9-r3[so:libcrypto.so.1.1]
               libssl1.1-1.1.1q-r0[so:libcrypto.so.1.1]
  libssl1.1-1.1.1q-r0:
    breaks: openssl-dev-1.1.1s-r0[libssl1.1=1.1.1s-r0]
    satisfies: world[libssl1.1=1.1.1q-r0]
               python3-3.10.5-r0[so:libssl.so.1.1]
               libpq-14.5-r0[so:libssl.so.1.1]
               libcurl-7.83.1-r2[so:libssl.so.1.1]
               apk-tools-2.12.9-r3[so:libssl.so.1.1]
  build-dependencies-20221104.164031:
    masked in: cache
    satisfies: world[build-dependencies=20221104.164031]
Removing intermediate container eada0d48d2e4
```

**Comment by jeroenterheerdt** [comment] 2022-11-04 16:46
I am on:
Home Assistant 2022.10.5
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221010.0 - latest

Raspberry 4

**Comment by OttPeterR** [comment] 2022-11-04 17:40
is this your first install or were you updating?

**Comment by jeroenterheerdt** [comment] 2022-11-04 18:08
first install

**Comment by jeroenterheerdt** [comment] 2022-11-04 18:08
are there pre-reqs I should somehow install first?

**Comment by jeroenterheerdt** [comment] 2022-11-04 18:47
also tried running the Dockerfile in the Portainer add-on, same result:

```
Step 1/12 : ARG BUILD_FROM=ghcr.io/hassio-addons/base/armv7:12.2.3



Step 2/12 : FROM ${BUILD_FROM}



 ---> 772ef21b4775

Step 3/12 : VOLUME ["/run"]



 ---> Using cache

 ---> a1f76178557a

Step 4/12 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]



 ---> Using cache

 ---> 27fae369c78a

Step 5/12 : RUN   echo "**** install build packages ****" &&   apk add --no-cache --virtual=build-dependencies     build-base     curl     jpeg-dev     libffi-dev     libxml2-dev     libxslt-dev     postgresql-dev     python3-dev     zlib-dev



 ---> Running in ff9ca8e74719

**** install build packages ****

fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/armv7/APKINDEX.tar.gz

fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/armv7/APKINDEX.tar.gz

ERROR: unable to select packages:

  musl-1.2.3-r0:
    breaks: musl-dev-1.2.3-r1[musl=1.2.3-r1]
    satisfies: world[musl=1.2.3-r0]
               apk-tools-2.12.9-r3[musl>=1.2]
               apk-tools-2.12.9-r3[so:libc.musl-armv7.so.1]
               pkgconf-1.8.0-r1[so:libc.musl-armv7.so.1]
               llvm13-13.0.1-r2[so:libc.musl-armv7.so.1]
               gcc-11.2.1_git20220219-r2[so:libc.musl-armv7.so.1]
               clang-13.0.1-r1[so:libc.musl-armv7.so.1]
               icu-dev-71.1-r2[so:libc.musl-armv7.so.1]
               g++-11.2.1_git20220219-r2[so:libc.musl-armv7.so.1]
               libffi-3.4.2-r1[so:libc.musl-armv7.so.1]
               tzdata-2022c-r0[so:libc.musl-armv7.so.1]
               patch-2.7.6-r7[so:libc.musl-armv7.so.1]
               libjpeg-turbo-2.1.3-r1[so:libc.musl-armv7.so.1]
               libxslt-1.1.35-r0[so:libc.musl-armv7.so.1]
               bash-5.1.16-r2[so:libc.musl-armv7.so.1]
               ca-certificates-20220614-r0[so:libc.musl-armv7.so.1]
               python3-3.10.5-r0[so:libc.musl-armv7.so.1]


               binutils-2.38-r3[so:libc.musl-armv7.so.1]
               busybox-1.35.0-r17[so:libc.musl-armv7.so.1]
               libecpg-dev-14.5-r0[so:libc.musl-armv7.so.1]
               sqlite-libs-3.38.5-r0[so:libc.musl-armv7.so.1]
               curl-7.83.1-r2[so:libc.musl-armv7.so.1]
               ncurses-libs-6.3_p20220521-r0[so:libc.musl-armv7.so.1]
               expat-2.5.0-r0[so:libc.musl-armv7.so.1]
               musl-utils-1.2.3-r0[so:libc.musl-armv7.so.1]
               nghttp2-libs-1.47.0-r0[so:libc.musl-armv7.so.1]
               llvm13-libs-13.0.1-r2[so:libc.musl-armv7.so.1]
               libstdc++-11.2.1_git20220219-r2[so:libc.musl-armv7.so.1]
               mpdecimal-2.5.1-r1[so:libc.musl-armv7.so.1]
               libbz2-1.0.8-r1[so:libc.musl-armv7.so.1]
               brotli-libs-1.0.9-r6[so:libc.musl-armv7.so.1]
               libpq-14.5-r0[so:libc.musl-armv7.so.1]
               libpq-dev-14.5-r0[so:libc.musl-armv7.so.1]
               clang-libs-13.0.1-r1[so:libc.musl-armv7.so.1]

               file-5.41-r0[so:libc.musl-armv7.so.1]
               icu-71.1-r2[so:libc.musl-armv7.so.1]
               libcurl-7.83.1-r2[so:libc.musl-armv7.so.1]
               mpc1-1.2.1-r0[so:libc.musl-armv7.so.1]
               libmagic-5.41-r0[so:libc.musl-armv7.so.1]
               gdbm-1.23-r0[so:libc.musl-armv7.so.1]
               icu-libs-71.1-r2[so:libc.musl-armv7.so.1]
               oniguruma-6.9.8-r0[so:libc.musl-armv7.so.1]
               mpfr4-4.1.0-r0[so:libc.musl-armv7.so.1]
               zlib-1.2.12-r3[so:libc.musl-armv7.so.1]
               libgomp-11.2.1_git20220219-r2[so:libc.musl-armv7.so.1]
               readline-8.1.2-r0[so:libc.musl-armv7.so.1]
               libecpg-14.5-r0[so:libc.musl-armv7.so.1]
               make-4.3-r0[so:libc.musl-armv7.so.1]
               libgpg-error-1.45-r0[so:libc.musl-armv7.so.1]
               libgcc-11.2.1_git20220219-r2[so:libc.musl-armv7.so.1]
               postgresql14-dev-14.5-r0[so:libc.musl-armv7.so.1]
               libssl1.1-1.1.1q-r0[so:libc.musl-armv7.so.1]


               alpine-baselayout-3.2.0-r22[so:libc.musl-armv7.so.1]
               libcrypto1.1-1.1.1q-r0[so:libc.musl-armv7.so.1]
               libatomic-11.2.1_git20220219-r2[so:libc.musl-armv7.so.1]
               xz-libs-5.2.5-r1[so:libc.musl-armv7.so.1]
               libxml2-2.9.14-r2[so:libc.musl-armv7.so.1]
               scanelf-1.3.4-r0[so:libc.musl-armv7.so.1]
               gmp-6.2.1-r2[so:libc.musl-armv7.so.1]
               jq-1.6-r1[so:libc.musl-armv7.so.1]
               libgcrypt-1.10.1-r0[so:libc.musl-armv7.so.1]
               isl22-0.22-r0[so:libc.musl-armv7.so.1]
  libcrypto1.1-1.1.1q-r0:
    breaks: openssl-dev-1.1.1s-r0[libcrypto1.1=1.1.1s-r0]
    satisfies: world[libcrypto1.1=1.1.1q-r0]
               ca-certificates-20220614-r0[so:libcrypto.so.1.1]
               python3-3.10.5-r0[so:libcrypto.so.1.1]
               libpq-14.5-r0[so:libcrypto.so.1.1]
               libcurl-7.83.1-r2[so:libcrypto.so.1.1]
               apk-tools-2.12.9-r3[so:libcrypto.so.1.1]
               libssl1.1-1.1.1q-r0[so:libcrypto.so.1.1]


  libssl1.1-1.1.1q-r0:
    breaks: openssl-dev-1.1.1s-r0[libssl1.1=1.1.1s-r0]
    satisfies: world[libssl1.1=1.1.1q-r0]
               python3-3.10.5-r0[so:libssl.so.1.1]
               libpq-14.5-r0[so:libssl.so.1.1]
               libcurl-7.83.1-r2[so:libssl.so.1.1]
               apk-tools-2.12.9-r3[so:libssl.so.1.1]
  build-dependencies-20221104.184630:
    masked in: cache
    satisfies: world[build-dependencies=20221104.184630]

The command '/bin/bash -o pipefail -c echo "**** install build packages ****" &&   apk add --no-cache --virtual=build-dependencies     build-base     curl     jpeg-dev     libffi-dev     libxml2-dev     libxslt-dev     postgresql-dev     python3-dev     zlib-dev' returned a non-zero code: 76


              
            ```

**Comment by OttPeterR** [comment] 2022-11-04 19:07
I've had similar dependency issues like this in the past, though I think it was openssl last time. I pushed an update for the base container, let me know if that does it for you!

**Comment by jeroenterheerdt** [comment] 2022-11-04 19:15
just tried it again, same result. how can I tell I am using the latest base container? The logs are identical. the Add-on install screen says '1.13.2.1' in the top-right, so I am assuming it's using the latest you just pushed:
![image](https://user-images.githubusercontent.com/8188990/200057611-cefea1b8-a961-4d8e-a47d-78fb2c386aac.png)

**Comment by OttPeterR** [comment] 2022-11-04 19:41
Yeah the 1.13.2.1 in the top right means you have the version I just pushed up
As for why the error is persisting... I'm not so sure. 
I can't get the issue to reproduce on my end and the first difference I see is that I'm on amd64 not armv7

**Comment by OttPeterR** [comment] 2022-11-04 19:48
Found the issue for the previous time this happened: #11 

My thought was that the dependency conflict was caused by some upstream dependency and it went away after a few days, since nothing I did seemed fix it. I'll keep a lookout for a new container version, but it may resolve itself on its own.

Sorry 😕 this isn't ideal but I think it's out of our control for now.

**Comment by jeroenterheerdt** [comment] 2022-11-04 21:01
ok, thanks for letting me know!

**Comment by jeroenterheerdt** [comment] 2022-11-06 01:59
still trying to figure this out, seems like the `build-base` package is the culprit (and potentially the `build-essential` as well). `alpine-sdk` doesn't help either. Cannot find a way around this, so unfortunately this is a no-go. Darn it.

**Comment by jeroenterheerdt** [comment] 2022-11-06 22:13
made some progress - replacing `build-base` with `gcc` helped. however, `postgresql-dev` is not included after Alpine 3.14 according to the package list: https://pkgs.alpinelinux.org/packages?name=postgresql-dev&branch=v3.14&repo=&arch=&maintainer=. 
That is now stopping me from progressing. I am unsure how to get the packages from 3.14 exclusively.

**Comment by OttPeterR** [comment] 2022-11-07 00:10
I went down a rabbit hole of dependency pinning and what not but also couldn't get to the bottom of it when this happened a few months ago 😕

**Comment by NobleWolf** [comment] 2022-11-07 19:19
Is there a previous version of you addon that did successfully install?

@jeroenterheerdt where are you currently hosting Baby Buddy?

I posted here as well. https://community.home-assistant.io/t/wip-baby-buddy-integration-frontend/464123/3?u=noblewolf If there is anything I can do for testing I'd be happy to help, but I have no experience in building add-ons or containers.

**Comment by jeroenterheerdt** [comment] 2022-11-07 22:51
hi @NobleWolf - this is my first try to install the add-on. I am not hosting it anywhere, I am trying to get it running on a container on HA on RPI 4 (arch armv7). I also tried running it on my laptop (arch x86_64) in case the architecture would be problematic and that seems to work. I am no expert either, but hoping someone can help getting this to work on armv7/rpi4

**Comment by SebRut** [comment] 2022-11-12 07:23
There seems to be a new release of the addon-base image https://github.com/hassio-addons/addon-base/releases/tag/v12.2.6 which seems to fix the build error at least for my local build. I'm not sure on how to test the armv7 build though.

**Comment by OttPeterR** [comment] 2022-11-12 20:27
thanks for finding that, I pushed out those changes just now, let me know if it fixes things for you @jeroenterheerdt

**Comment by NobleWolf** [comment] 2022-11-12 20:48
![Screenshot_20221112-144549_Home Assistant.jpg](https://user-images.githubusercontent.com/5035544/201493927-b8939c55-5967-417a-9f69-cb6593b4cdac.jpg)

I just tried to install version 1.13.2.2 and got this error.

I'm on a Raspberry Pi 3b+ running late at HA Supervised and HA OS.

**Comment by NobleWolf** [comment] 2022-11-12 20:49
![Screenshot_20221112-144549_Home Assistant.jpg](https://user-images.githubusercontent.com/5035544/201493927-b8939c55-5967-417a-9f69-cb6593b4cdac.jpg)

I just tried to install version 1.13.2.2 and got this error.

**Comment by chpego** [comment] 2022-11-12 21:53
> thanks for finding that, I pushed out those changes just now, let me know if it fixes things for you @jeroenterheerdt

Mmmmh did you forget to bump version in build.yaml file  ?
https://github.com/OttPeterR/addon-babybuddy/blob/b3d7bf7faa1f1905d470a795d49a5698edb273c9/babybuddy/build.yaml#L3-L7

**Comment by chpego** [comment] 2022-11-12 22:03
It's using **amd64 arch**, maybe changing this line ?
https://github.com/OttPeterR/addon-babybuddy/blob/b3d7bf7faa1f1905d470a795d49a5698edb273c9/babybuddy/Dockerfile#L1

**Comment by OttPeterR** [comment] 2022-11-12 23:48
I did forget that build.yaml, thanks - that's pushed up now as well

that said, I was able to replicate the issue on my end (finally) but still have no luck in resolving the issue 😞

**Comment by chpego** [comment] 2022-11-13 08:21
I've the same problem, now

I think the addon base image need to upgrade library **musl to  1.2.3-r2**

https://github.com/hassio-addons/addon-base/blob/d711941d487306313a91a066633d48c1bae26f46/base/Dockerfile#L41-L42

**Comment by jeroenterheerdt** [comment] 2022-11-13 20:53
Thanks fo updating, still seeing the same problem. I think @choego is correct, the base image should update the musl package.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jampez77** [comment] 2022-11-14 09:03
I'm getting a similar error when upgrading from 1.13.2.2 to 1.13.2.3
<img width="1280" alt="Screenshot 2022-11-14 at 09 02 53" src="https://user-images.githubusercontent.com/1823647/201618841-379ad041-22fb-49eb-9770-b11c0552c642.png">

**Comment by chpego** [comment] 2022-11-15 05:31
@OttPeterR could you upgrade the base image , the PR has been merged 😁

https://github.com/hassio-addons/addon-base/releases/tag/v12.2.7

**Comment by OttPeterR** [comment] 2022-11-15 11:08
12.2.7 is pushed

**Comment by SebRut** [comment] 2022-11-15 11:59
> 12.2.7 is pushed

I was able to install the addon now. Start is looking good as well.

**Comment by OttPeterR** [comment] 2022-11-15 13:01
Glad to hear it, I'll close out this issue 👍🏻

**Closed as completed** 2022-11-15 13:01 UTC

**Comment by jeroenterheerdt** [comment] 2022-11-15 20:05
FWIW - I can confirm it works on armv7 for me as well now. Thank you! Hope to see ingress working at some point as well - any ideas on that?

**Comment by OttPeterR** [comment] 2022-11-15 20:11
I'm in school right now so I don't anticipate putting much work into it until winter break, so I'd expect some update around December/January
