### ISSUE TITLE
Access via Home Assistant sidebar

### ISSUE THREAD

**Issue by jwildman16** [OttPeterR/addon-babybuddy#24] opened 2022-12-04 17:21 UTC
I followed the instructions to set up HTTPS access and I'm able to access BB via https://babybuddy._mydomain_.duckdns.org, but when I click on the BB link from the Home Assistant sidebar, I get a 404 Not Found error. Any ideas why?

**Comment by OttPeterR** [comment] 2022-12-05 05:05
Dupe of #2

**Closed as completed** 2022-12-05 05:05 UTC
