### ISSUE TITLE
Getting error : 502: Bad Gateway while trying to load it.

### ISSUE THREAD

**Issue by fpsacha** [OttPeterR/addon-babybuddy#7] opened 2022-05-20 19:13 UTC
I installed the addon from HACS.

**Comment by jampez77** [comment] 2022-05-21 03:39
This is a duplicate of issue https://github.com/OttPeterR/addon-babybuddy/issues/2

**Comment by OttPeterR** [comment] 2022-05-21 08:01
Closing duplicate issue (#2)

**Closed as completed** 2022-05-21 08:01 UTC
